### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter' on MacOS

### ISSUE THREAD

**Issue by nikhilrayaprolu** [vishalv26/covid-vaccine-booking#13]

**Comment by nikhilrayaprolu** [comment]
```
Traceback (most recent call last):
  File "/Users/nikhil/Downloads/covid-vaccine-booking/src/covid-vaccine-slot-booking.py", line 7, in <module>
    from utils import generate_token_OTP, check_and_book, beep, BENEFICIARIES_URL, WARNING_BEEP_DURATION, \
  File "/Users/nikhil/Downloads/covid-vaccine-booking/src/utils.py", line 5, in <module>
    from captcha import captcha_builder
  File "/Users/nikhil/Downloads/covid-vaccine-booking/src/captcha.py", line 3, in <module>
    import PySimpleGUI as sg
  File "/usr/local/lib/python3.9/site-packages/PySimpleGUI/__init__.py", line 2, in <module>
    from .PySimpleGUI import *
  File "/usr/local/lib/python3.9/site-packages/PySimpleGUI/PySimpleGUI.py", line 96, in <module>
    import tkinter as tk
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 37, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by vishalv26** [comment]
Did you perform `pip install -r requirements.txt`
