### ISSUE TITLE
Error executing file

### ISSUE THREAD

**Issue by Vicky1812** [vishalv26/covid-vaccine-booking#3]
Getting the following response on executing the file in a windows laptop

Traceback (most recent call last):
  File "C:\Users\premj\Desktop\Cowin\src\covid-vaccine-slot-booking.py", line 108, in <module>
    main()
  File "C:\Users\premj\Desktop\Cowin\src\covid-vaccine-slot-booking.py", line 20, in main
    beep(500, 150)
  File "C:\Users\premj\Desktop\Cowin\src\utils.py", line 37, in beep
    winsound.Beep(freq, duration)
RuntimeError: Failed to beep

**Comment by vishalv26** [comment]
Thanks for notifying. This is fixed now. Please download again and run.

**Comment by Vicky1812** [comment]
Thanks for the quick fix 👍
